### ISSUE TITLE
Could you support auto reconnect feature in the client side?

### ISSUE THREAD

**Issue by zzczzc004** [MhAllan/TcpServiceCore#15]
I want to implement the auto reconnect feature, In my case, the network in client side is not stable, if the network is broken, I can store my some requests and send them when the connection is recover. Could you give me some advice to implement this feature or encapsulate this feature into lib?

**Comment by MhAllan** [comment]
I think you better invoke the action if it throws because of connectivity you create new proxy. but I added the state event as well

        async Task CreateClient()
        {
            this.client = await ChannelFactory<IService>.CreateProxy("localhost", 9091, config);
            var channel = (IClientChannel)client;
            channel.StateChanged += StateChanged;
            await channel.Open();
        }

        async void StateChanged(ICommunicationObject client, CommunicationState state)
        {
            if (state != CommunicationState.Opened)
            {
                var channel = (IClientChannel)client;
                channel.StateChanged -= StateChanged;
                channel.Dispose();
                await CreateClient();
            }
        }

**Comment by zzczzc004** [comment]
Thank for you reply, I try the method you suggest, it can solve the connect problem when first time. I use a Timer to ensure `CreateClient()` is invoked successful, if failed, I will try to invoke it several seconds later.

But after I connect server first time, when the connection get lost again, how can I detect this case and try to reconnect again. I see the `StateChanged` is only called when **Open** and **Close**.
