### ISSUE TITLE
Callback contract

### ISSUE THREAD

**Issue by hdimon** [MhAllan/TcpServiceCore#18]
Hi!

Could you please implement callbacks? I see in code there is something related to it but can't make it work. If it should work could you please give example how to work with it?

Thanks in advance!

**Comment by MhAllan** [comment]
Hi @hdimon , The framework is not complete, buffers and memory need more work, also the code need to be simplified and cleaned. unfortunately I have no time for it now plus it didn't gain contribution from the society. if you can use SignalR Core with WebSockets then that's a better solution. If TCP is must for you or you want to host service in Apps then I will find you time to implement the callback, but again, this is not solid framework.

**Comment by MhAllan** [comment]
Hi @hdimon , The framework is not complete, buffers and memory need more work, also the code need to be simplified and cleaned. unfortunately I have no time for it now plus it didn't gain contribution from the community. if you can use SignalR Core with WebSockets then that's a better solution.
